export const CLASS_SUBJECTS = {
  COMMON: ["MATH", "ENGLISH", "SCIENCE", "CIVICS", "BIOLOGY"],

  "10E": ["HISTORY", "POA", "COMMERCE"],
  "10K": ["PHYSICAL_EDUCATION", "BEMBA", "RELIGIOUS_EDUCATION"],
  "10Z": ["RELIGIOUS_EDUCATION", "GEOGRAPHY", "FOOD_OR_DESIGN"],

  "11E": ["HISTORY", "POA", "COMMERCE"],
  "11K": ["PHYSICAL_EDUCATION", "BEMBA", "RELIGIOUS_EDUCATION", "LITERATURE"],
  "11Z": ["RELIGIOUS_EDUCATION", "GEOGRAPHY"],

  "12E": ["HISTORY", "POA", "COMMERCE"],
  "12K": ["PHYSICAL_EDUCATION", "BEMBA", "RELIGIOUS_EDUCATION"],
  "12Z": ["RELIGIOUS_EDUCATION", "GEOGRAPHY"],
  "12L": ["ADDITIONAL_MATH", "GEOGRAPHY", "CHEMISTRY", "PHYSICS"]
};

export function getSubjects(className) {
  return [
    ...(CLASS_SUBJECTS.COMMON || []),
    ...(CLASS_SUBJECTS[className] || [])
  ];
}